apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentevals.fullname" . }}
  labels:
    {{- include "agentevals.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.uiPort }}
      targetPort: http
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.otlpPort }}
      targetPort: otlp-http
      protocol: TCP
    - name: mcp
      port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
  selector:
    {{- include "agentevals.selectorLabels" . | nindent 4 }}
